name: API Documentation Validation

on:
  push:
    branches: [main]
    paths:
      - 'packages/api/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/api/**'
  workflow_dispatch:

jobs:
  validate-api-docs:
    name: Validate API Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.6.0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build API package
        run: pnpm --filter "@kbstack/api" build
      - name: Validate OpenAPI schema
        run: |
          npx @openapitools/openapi-generator-cli validate \
            --recommend \
            -i <(node -e "console.log(JSON.stringify(require('./packages/api/dist/swagger').openApiDocument))")
      - name: Generate API documentation
        run: |
          mkdir -p api-docs
          npx @redocly/cli build-docs \
            --output=api-docs/index.html \
            <(node -e "console.log(JSON.stringify(require('./packages/api/dist/swagger').openApiDocument))")
      - name: Upload API documentation
        uses: actions/upload-artifact@v4
        with:
          name: api-documentation
          path: api-docs
